# -*- coding: utf-8 -*-
"""Project1 with Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYqXgMpsdcTQUbGUL1f2RH6jpvKs9ls9

importing libraries
"""

import numpy as np
import pandas as pd

"""Choosing dataset file from local"""

from google.colab import files
uploaded=files.upload()

"""Loading the dataset """

dataset=pd.read_csv('Flowers dataset.csv')
print(dataset)

"""Summarize Dataset"""

print(dataset.shape)
print(dataset.head(5))

"""Segregate x and Y"""

x=dataset.iloc[:,:-1].values
x

y=dataset.iloc[:,-1].values
y

"""SPLIT FOR TRAIN AND TEST

"""

import sklearn 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

"""TRAINING"""

from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model1.fit(x_train,y_train)

"""PREDICTION for test data"""

y_pred=model1.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

"""ACCURACY"""

from sklearn.metrics import accuracy_score
print("accuracy of the model: {0}%".format(accuracy_score(y_test,y_pred)*100))

"""Predit the flower based on the feature"""

sepal_width=int(input("Enter the sepal width :"))
sepal_length=int(input("Enter the sepal length :"))
Petal_width=int(input("Enter the petal width:"))
Petal_length=int(input("Enter the petal length :"))
newflower=[[sepal_width,sepal_length,Petal_width,Petal_length]]
result=model1.predict((newflower))
print(result)



"""# New Section"""